apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pv-config
data:
  storage: "5Gi"
  accessModes: "ReadWriteOnce"
  claimName: "mysql-pv-claim"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
