apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
namespace: default
data:
	dbname: <base64 encoded string of dbname>
	dbpassword: <base64 encoded string of dbpassword>
	dbrootpassword: <base64 encoded string of dbrootpassword>
	dbuser: <base64 encoded string of dbuser>
type: Opaque